GET http://localhost:5055/games

###
GET http://localhost:5055/games/4

### 
POST http://localhost:5055/games
Content-Type: application/json

{
  "Name": "Elden Ring",
  "GenreId": 4,
  "Price": 59.99,
  "ReleaseDate": "2022-02-25"
}
###
PUT http://localhost:5055/games/4
Content-Type: application/json

{
  "Name": "Edited EditedEdidiiiid",
  "GenreId": 1, 
  "price": 30543.99,
  "releaseDAte": "2015-05-19"
}

###
DELETE  http://localhost:5055/games/11
